Ppc/Ppc/Controllers/PostcardsController.cs
#define _LOCAL 

using Ppc.Models;


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ppc.Controllers
{
    public class PostcardsController : Controller
    {
        // GET: Postcards
        public ActionResult Index()
        {
			List<Postcard> pl = null;

#if _LOCAL

			pl = new List<Postcard>() {

				new Postcard() { Id = 1, Name = "postcard 1", Url = "/img/postcards/Castle.jpg" },
				new Postcard() { Id = 2, Name = "postcard 2", Url = "/img/postcards/Earl.jpg" },
				new Postcard() { Id = 3, Name = "postcard 3", Url = "/img/postcards/Gold.jpg" },
				new Postcard() { Id = 4, Name = "postcard 4", Url = "/img/postcards/GroundFloor.jpg" },
			};
#else
			pl = new List<Postcard>() {

				new Postcard() { Id = 1, Name = "postcard 1", Url = "/new/img/postcard-packs/1/Alice-Groundfloor-TIFF.jpg" },
				new Postcard() { Id = 1, Name = "postcard 2", Url = "/new/img/postcard-packs/1/Castle.jpg" },
				new Postcard() { Id = 1, Name = "postcard 3", Url = "/new/img/postcard-packs/1/Earl.jpg" },
				new Postcard() { Id = 1, Name = "postcard 4", Url = "/new/img/postcard-packs/1/Electric-Entrance - Tiff.jpg" },
				new Postcard() { Id = 1, Name = "postcard 5", Url = "/new/img/postcard-packs/1/Finchs-Mini-TIFF.jpg" },
				new Postcard() { Id = 1, Name = "postcard 6", Url = "/new/img/postcard-packs/1/Gold-Betsie-TIFF.jpg" },
				new Postcard() { Id = 1, Name = "postcard 7", Url = "/new/img/postcard-packs/1/Gold.jpg" },
				new Postcard() { Id = 1, Name = "postcard 8", Url = "/new/img/postcard-packs/1/GroundFloor.jpg" },
				new Postcard() { Id = 1, Name = "postcard 9", Url = "/new/img/postcard-packs/1/Jockey-Strongbow.jpg" },
				new Postcard() { Id = 1, Name = "postcard 10", Url = "/new/img/postcard-packs/1/Jockey_and-Buster-The-Sun-in-Splender (1).jpg" },
				new Postcard() { Id = 1, Name = "postcard 11", Url = "/new/img/postcard-packs/1/London-Bus.jpg" },
				new Postcard() { Id = 1, Name = "postcard 12", Url = "/new/img/postcard-packs/1/Portobello-fruit-and-veg-stall -TIFF.jpg" },
			};

#endif
			return View(pl);
        }
    }
}

Ppc/Ppc/Controllers/TailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ppc.Controllers
{
    public class TailController : Controller
    {
        // GET: Stories
        public ActionResult Index()
        {
            return View();
        }
    }
}

Ppc/Ppc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

	<meta property="og:url" content="http://portobellopostcards.co.uk" />
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Portobello Postcards" />
	<meta property="og:description" content="Portobello Postcards" />
	<meta property="og:image" content="~/img/home/home-cafe-scene.jpg" />

	<title>Portobello Postcards - @ViewBag.Title</title>
	@Styles.Render("~/Content/css")
	@*@Scripts.Render("~/bundles/modernizr")*@
	@*<link rel="stylesheet" href="~/Content/jquery.Jcrop.min.css" type="text/css" />*@
	<link rel="stylesheet" href="~/Content/animate.css" type="text/css" />
</head>

<body>

	<div class="container-fluid">

		<div class="row">
			<header>
				<div class="navbar navbar-default navbar-fixed-top">
					<div class="container">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
						</div>
						<div id="navbar" class="navbar-collapse collapse">
							<ul class="nav navbar-nav navbar-right">
								<li>
									@Html.ActionLink("Portobello Postcards", "Index", "Postcards")
								</li>

								<li>
									@Html.ActionLink("Portobello Tail", "Index", "Tail")
								</li>
							</ul>
						</div>
					</div>
				</div>
			</header>
		</div>

		<div class="row">
			@RenderBody()
		</div>

		<div class="row">
			<footer>

				<div id="ticker" class="ticker full-width">

					@for (int i = 0; i < 10; i++)
					{
						<span>
							<img class="ticker-img"
								 src="~/img/ticker/buster-jockey-2-rev-sm.jpg" />
						</span>
						<span class="blurb-text">
							<i>
								Postcards are for sale outside <a href="#"
														  data-toggle="modal"
														  data-target="#mapModal">
									177 Portobello Road London W11 2DY
								</a>
							</i>
						</span>
					}
				</div>
				<p>&copy; @DateTime.Now.Year - The Original Portobello Postcard Company Ltd.</p>
			</footer>
		</div>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)

	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCdKVJFl9kH_0wYiMbm_KnQo8OSOKGv3Gc"
			type="text/javascript">
	</script>

	<script src="~/Scripts/jquery.mobile.custom.min.js"></script>
	<script src="~/Scripts/endless_scroll_min.js"></script>
	<script src="~/Scripts/jquery.panzoom.min.js"></script>
	<script src="~/Scripts/single-double-click.js"></script>
	@*<script src="~/Scripts/jquery.Jcrop.min.js"></script>*@

	<script>

		var map;
		var lat = 51.514958;
		var lon = -0.204645;

		function resetMap() {

			map.setCenter(new google.maps.LatLng(lat, lon));
			map.setZoom(20);
			map.setMapTypeId(google.maps.MapTypeId.ROADMAP);

			nudgeMap();
		}

		function nudgeMap() {

			google.maps.event.trigger(map, 'resize');

			map.setZoom(map.getZoom() - 1);
			map.setZoom(map.getZoom() + 1);
		}

		function initMap() {

			map = new google.maps.Map(document.getElementById("map"));

			resetMap();

			google.maps.event.addListener(map, "idle", function () {

				nudgeMap();
			});

			$("a[data-toggle=modal]").click(function () {
				resetMap();
			});
		}

	</script>

	@*<script>
			//function loadModalCanvas(url) {

			//	var canvas = document.getElementById('imgModalImg');
			//	var context = canvas.getContext('2d');

			//		var img = new Image();
			//		img.onload = function () {

			//			context.drawImage(this, 0, 0);
			//	};

			//	img.src = url;
			//}
		</script>*@

	<script>

		$(document).ready(function () {

			$("#ticker").endlessScroll(
				{
					steps: -2,
					speed: 30,
					mousestop: false
				});

			$("#imgModalImg").panzoom({
				//$zoomIn: $(".zoom-in"),
				//$zoomOut: $(".zoom-out"),
				//$zoomRange: $(".zoom-range"),
				//$reset: $(".reset"),
				cursor: "crosshair",
				transition: true,
				increment: 0.5
			});

			$("#imgModalImg").single_double_click(function (e) {

				//var w = $(this).width();
				//var h = $(this).height();

				//var x = w - e.clientX;
				//var y = h - e.clientY;

				//$("#imgModalImg").panzoom("pan", x, y, {
				//	relative: true,
				//	animate: true
				//});
				$("#imgModalImg").panzoom("zoom");
			},
			function (e) {
				//$("#imgModalImg").panzoom("pan", 250, 250, {
				//	relative: true,
				//	animate: true
				//});
				$("#imgModalImg").panzoom("zoom", true);
			});

			$(".modal-img-dblclickable").dblclick(function (e) {

				$("#imgModalImg").panzoom("reset");

				var url = $(this).prop("src");

				//loadModalCanvas(url);

				$("#imgModalImg").prop("src", url);

				$("#imgModal").modal('toggle');
			});

			initMap();

			//$(window).resize(function () {

			//});
		});

	</script>

	@*<script src="https://apis.google.com/js/platform.js" async defer></script>*@

	<div id="mapModal" class="modal fade" role="dialog">

		<div class="modal-dialog">
			<div id="mapBody" class="modal-body">
				<input type="button" class="btn btn-default pull-right" data-dismiss="modal" value="Close" />
				<div id="map"
					 class="modal-img"
					 style="width:600px; height: 600px">

				</div>
			</div>
		</div>

	</div>

	<div id="imgModal" class="modal fade" role="dialog">

		<div class="modal-dialog">

			<div class="modal-header">

				<input type="button" class="btn btn-default pull-right"
					   data-dismiss="modal" value="Close" />
			</div>

			<div class="modal-body">
				<div id="imgModalImgContainer">

					@*<canvas id="imgModalImg"
						width="800"
						height="800"></canvas>*@
					<img id="imgModalImg"
						 class="img-responsive modal-img" />
				</div>
			</div>
		</div>
	</div>
</body>


@*lat = 51.514958
	lon = -0.204645*@

@*google map api browser key AIzaSyCdKVJFl9kH_0wYiMbm_KnQo8OSOKGv3Gc*@

</html>