old/ppc/PPC/Controllers/Admin/AdminImageContentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using System.IO;

namespace WebApp.Controllers.Admin
{
	public class AdminImageContentsController : AdminController
    {
		private const string _IMG_DIR = "~/images";
		private const string _UPLOAD_DIR = "~/App_Data/uploads";

        private PortobelloPostcardsDbContext db = new PortobelloPostcardsDbContext();

        // GET: ImageContents
        public ActionResult Index()
        {
            return View(db.ImageContent.ToList());
        }

        // GET: ImageContents/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageContent imageContent = db.ImageContent.Find(id);
            if (imageContent == null)
            {
                return HttpNotFound();
            }
            return View(imageContent);
        }

		private string MoveUploadImage(HttpPostedFileBase file)
		{
			string url = string.Empty;

			string fileName = Path.GetFileName(file.FileName);
			string path = Path.Combine(Server.MapPath(_UPLOAD_DIR), fileName);

			file.SaveAs(path);

			string newPath = Path.Combine(Server.MapPath(_IMG_DIR), Path.GetFileName(path));

			System.IO.File.Delete(newPath);

			System.IO.File.Move(path, newPath);

			url = Path.Combine(_IMG_DIR, fileName).Replace('\\', '/');

			return url;
		}

		[HttpPost]
		public ActionResult Upload([Bind(Include = "Id,Url,Description,Placeholder,MimeType")]ImageContent imageContent, HttpPostedFileBase file)
		{
			if (null != imageContent && null != file)
			{
				if (ModelState.IsValid)
				{
					imageContent.MimeType = file.ContentType;

					imageContent.Url = MoveUploadImage(file).TrimStart(new char[] { '~', '/', });

					ImageContent ic = db.ImageContent.Where(t => t.Id == imageContent.Id).FirstOrDefault();

					if (null == ic)
						db.ImageContent.Add(imageContent);
					else
					{
						ic.Url = imageContent.Url;
						ic.Description = imageContent.Description;
						ic.MimeType = imageContent.MimeType;
						ic.Placeholder = imageContent.Placeholder;

						db.Entry(ic).State = EntityState.Modified;
					}

					db.SaveChanges();
				}
			}

			return RedirectToAction("Index");
		}






        // GET: ImageContents/Create
        public ActionResult Create()
        {
            return View();
        }

		////////// POST: ImageContents/Create
		////////// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		////////// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		////////[HttpPost]
		////////[ValidateAntiForgeryToken]
		////////public ActionResult Create([Bind(Include = "Id,Url,Description,Placeholder,MimeType")] ImageContent imageContent)
		////////{
		////////	if (ModelState.IsValid)
		////////	{
		////////		db.ImageContent.Add(imageContent);
		////////		db.SaveChanges();
		////////		return RedirectToAction("Index");
		////////	}

		////////	return View(imageContent);
		////////}

        // GET: ImageContents/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageContent imageContent = db.ImageContent.Find(id);
            if (imageContent == null)
            {
                return HttpNotFound();
            }
            return View(imageContent);
        }

		////////// POST: ImageContents/Edit/5
		////////// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		////////// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		////////[HttpPost]
		////////[ValidateAntiForgeryToken]
		////////public ActionResult Edit([Bind(Include = "Id,Url,Description,Placeholder,MimeType")] ImageContent imageContent)
		////////{
		////////	if (ModelState.IsValid)
		////////	{
		////////		db.Entry(imageContent).State = EntityState.Modified;
		////////		db.SaveChanges();
		////////		return RedirectToAction("Index");
		////////	}
		////////	return View(imageContent);
		////////}

        // GET: ImageContents/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageContent imageContent = db.ImageContent.Find(id);
            if (imageContent == null)
            {
                return HttpNotFound();
            }
            return View(imageContent);
        }

        // POST: ImageContents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ImageContent imageContent = db.ImageContent.Find(id);
            db.ImageContent.Remove(imageContent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

old/ppc/PPC/Views/AdminImageContents/Create.cshtml
@model WebApp.Models.ImageContent

@{
    ViewBag.Title = "Create";
}
<div>
<h2>Create</h2>

@using (Html.BeginForm("Upload", "AdminImageContents", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ImageContent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Placeholder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Placeholder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Placeholder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MimeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MimeType, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			<label for="file">Filename:</label>
			<input type="file" name="file" id="file" />
		</div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

old/ppc/PPC/Views/AdminImageContents/Delete.cshtml
@model WebApp.Models.ImageContent

@{
    ViewBag.Title = "Delete";
}

<div>
	<h2>Delete</h2>

	<h3>Are you sure you want to delete this?</h3>
	<div>
		<h4>ImageContent</h4>
		<hr />
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.Url)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Url)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Description)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Description)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Placeholder)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Placeholder)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.MimeType)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.MimeType)
			</dd>

		</dl>

		@using (Html.BeginForm())
		{
			@Html.AntiForgeryToken()

			<div class="form-actions no-color">
				<input type="submit" value="Delete" class="btn btn-default" /> |
				@Html.ActionLink("Back to List", "Index")
			</div>
		}
	</div>
</div>

old/ppc/PPC/Views/AdminImageContents/Details.cshtml
@model PortobelloPostCardsCoUk.Models.ImageContent

@{
    ViewBag.Title = "Details";
}
<div>
	<h2>Details</h2>

	<div>
		<h4>ImageContent</h4>
		<hr />
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.Url)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Url)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Description)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Description)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Placeholder)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Placeholder)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.MimeType)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.MimeType)
			</dd>

		</dl>

		<img src="@Url.Content("~/" + Model.Url)" alt="body" />

	</div>
	<p>
		@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
		@Html.ActionLink("Back to List", "Index")
	</p>
</div>

old/ppc/PPC/Views/AdminImageContents/Edit.cshtml
@model WebApp.Models.ImageContent

@{
    ViewBag.Title = "Edit";
}

<div>
	<h2>Edit</h2>

	@using (Html.BeginForm("Upload", "AdminImageContents", FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			<h4>ImageContent</h4>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.Id)

			<div class="form-group">
				@Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Placeholder, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Placeholder, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Placeholder, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.MimeType, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.MimeType, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.MimeType, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<label for="file">Filename:</label>
				<input type="file" name="file" id="file" />
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Save" class="btn btn-default" />
				</div>
			</div>


			<img src="@Url.Content("~/" + Model.Url)" alt="body" />
		</div>
	}



	<div>
		@Html.ActionLink("Back to List", "Index")
	</div>
</div>

old/ppc/PPC/Views/AdminImageContents/Index.cshtml
@model IEnumerable<WebApp.Models.ImageContent>

@{
    ViewBag.Title = "Index";
}
<div>
	<h2>Index</h2>

	<p>
		@Html.ActionLink("Create New", "Create")
	</p>
	<table class="table">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Url)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Description)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Placeholder)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.MimeType)
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Url)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Placeholder)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.MimeType)
				</td>
				<td>
					@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
					@Html.ActionLink("Details", "Details", new { id = item.Id }) |
					@Html.ActionLink("Delete", "Delete", new { id = item.Id })
				</td>
			</tr>
		}

	</table>
</div>