old/ppc/PPC/Controllers/Admin/AdminProductItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
//using WebApp.Controllers.Attributes;

namespace WebApp.Controllers.Admin
{
	//[SlugToProductItemsIdAttribute]
    public class AdminProductItemsController : AdminController
    {
        private PortobelloPostcardsDbContext db = new PortobelloPostcardsDbContext();

        // GET: AdminProductItems
        public ActionResult Index(long? id)
        {
            if (null == id)
                return View(db.ProductItems.ToList());
            else
            {
                ViewData["id"] = id;
                var items = db.ProductItems.Where(p => p.ProductId == id);

                return View(items.ToList());
            }
        }

        // GET: AdminProductItems/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductItem productItem = db.ProductItems.Find(id);
            if (productItem == null)
            {
                return HttpNotFound();
            }
            return View(productItem);
        }

        // GET: AdminProductItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminProductItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "Id,ProductId,Sku,Size,Length,Width,Height,Colour,Price1,Price5,Price10,Price100,Price500,Price1000,Name,Slug,Description")] ProductItem productItem)
        {
            if (ModelState.IsValid)
            {
				productItem.UUid = new Guid();

                db.ProductItems.Add(productItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productItem);
        }

        // GET: AdminProductItems/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductItem productItem = db.ProductItems.Find(id);
            if (productItem == null)
            {
                return HttpNotFound();
            }
            return View(productItem);
        }

        // POST: AdminProductItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "Id,ProductId,Sku,Size,Length,Width,Height,Colour,Price1,Price5,Price10,Price100,Price500,Price1000,Name,Slug,Description")] ProductItem productItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productItem);
        }

        // GET: AdminProductItems/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductItem productItem = db.ProductItems.Find(id);
            if (productItem == null)
            {
                return HttpNotFound();
            }
            return View(productItem);
        }

        // POST: AdminProductItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ProductItem productItem = db.ProductItems.Find(id);
            db.ProductItems.Remove(productItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

old/ppc/PPC/Controllers/Admin/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
//using WebApp.Controllers.Attributes;

namespace WebApp.Controllers.Admin
{
	//[SlugToProductIdAttribute]
    public class AdminProductsController : AdminController
    {
        private PortobelloPostcardsDbContext db = new PortobelloPostcardsDbContext();

        // GET: AdminProducts
        public ActionResult Index(long? id)
        {
            if (null == id)
                return View(db.Products.ToList());
            else
            {
                ViewData["id"] = id;
                var products = db.Products.Where(p => p.ProductGroupId == id);

                return View(products.ToList());
            }
        }

        // GET: AdminProducts/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: AdminProducts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "Id,ProductGroupID,Name,Slug,Description")] Product product)
        {
            if (ModelState.IsValid)
            {
				product.UUid = Guid.NewGuid();

                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: AdminProducts/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: AdminProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "Id,ProductGroupID,Name,Slug,Description")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: AdminProducts/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: AdminProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

old/ppc/PPC/Views/AdminProducts/Create.cshtml
@model WebApp.Models.Product

@{
    ViewBag.Title = "Create";
}
<div>
	<h2>Create</h2>


	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			<h4>Product</h4>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			<div class="form-group">
				@Html.LabelFor(model => model.ProductGroupId, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.ProductGroupId, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.ProductGroupId, "", new { @class = "text-danger" })
				</div>
			</div>
			<div class="form-group">
				@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Create" class="btn btn-default" />
				</div>
			</div>
		</div>
	}

	<div>
		@Html.ActionLink("Back to List", "Index")
	</div>
	</div>
	@section Scripts {
		@Scripts.Render("~/bundles/jqueryval")
	}

old/ppc/PPC/Views/AdminProducts/Delete.cshtml
@model WebApp.Models.Product

@{
    ViewBag.Title = "Delete";
}
<div>
	<h2>Delete</h2>

	<h3>Are you sure you want to delete this?</h3>
	<div>
		<h4>Product</h4>
		<hr />
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.ProductGroupId)
			</dt>
			<dt>
				@Html.DisplayNameFor(model => model.ProductGroupId)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Name)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Slug)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Slug)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Description)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Description)
			</dd>

		</dl>

		@using (Html.BeginForm())
		{
			@Html.AntiForgeryToken()

			<div class="form-actions no-color">
				<input type="submit" value="Delete" class="btn btn-default" /> |
				@Html.ActionLink("Back to List", "Index")
			</div>
		}
	</div>
</div>

old/ppc/PPC/Views/AdminProducts/Details.cshtml
@model WebApp.Models.Product

@{
    ViewBag.Title = "Details";
}
<div>
	<h2>Details</h2>

	<div>
		<h4>Product</h4>
		<hr />
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.ProductGroupId)
			</dt>
			<dt>
				@Html.DisplayNameFor(model => model.ProductGroupId)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Name)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Slug)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Slug)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Description)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Description)
			</dd>

		</dl>
	</div>
	<p>
		@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
		@Html.ActionLink("Back to List", "Index")
	</p>
</div>

old/ppc/PPC/Views/AdminProducts/Edit.cshtml
@model WebApp.Models.Product

@{
    ViewBag.Title = "Edit";
}
<div>
	<h2>Edit</h2>


	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			<h4>Product</h4>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.Id)

			<div class="form-group">
				@Html.LabelFor(model => model.ProductGroupId, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.ProductGroupId, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.ProductGroupId, "", new { @class = "text-danger" })
				</div>

			</div>
			<div class="form-group">
				@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Save" class="btn btn-default" />
				</div>
			</div>
		</div>
	}

	<div>
		@Html.ActionLink("Back to List", "Index")
	</div>
</div>
	@section Scripts {
		@Scripts.Render("~/bundles/jqueryval")
	}

old/ppc/PPC/Views/AdminProducts/Index.cshtml
@model IEnumerable<WebApp.Models.Product>

@{
    ViewBag.Title = "Products";
}
<div>
	<p>
		@Html.ActionLink("Create New", "Create")
	</p>

	<p>
		@*<div>@Html.DisplayText("Products in Group " + Model.First().ProductGroupId.ToString())</div>*@

		<div>@Html.DisplayText("Products in Group " + @ViewData["pg_id"])</div>
	</p>

	<table class="table">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.ProductGroupId)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Slug)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Description)
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.ProductGroupId)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Slug)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td>
					@Html.ActionLink("Items", "Index", "AdminProductItems", new { id = item.Id }, null) |
					@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
					@Html.ActionLink("Details", "Details", new { id = item.Id }) |
					@Html.ActionLink("Delete", "Delete", new { id = item.Id })
				</td>
			</tr>
		}

	</table>
</div>